#!/usr/bin/env python3
"""Generate per-backend voice profiles for flagship voices.

Reads voices/{name}.json for each flagship name, writes per-backend slugged
profiles that share the existing ref WAV and reference_text.

Usage:
    python scripts/reclone-flagship.py           # skip-if-exists
    python scripts/reclone-flagship.py --force   # overwrite existing
"""
from __future__ import annotations

import argparse
import json
import os
import sys

# Make `backends` importable when run from repo root.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import backends

FLAGSHIPS = ["picard", "galadriel", "attenborough"]
# Non-default backends to generate profiles for (default is qwen3-0.6b, already present).
NON_DEFAULT_BACKENDS = ["qwen3-1.7b", "chatterbox", "voxcpm-1.5"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--force", action="store_true", help="Overwrite existing profiles")
    parser.add_argument(
        "--voices-dir",
        default=os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "voices"),
        help="Path to voices/ directory",
    )
    args = parser.parse_args()

    backends.register_all()

    written = 0
    skipped = 0
    for name in FLAGSHIPS:
        src_path = os.path.join(args.voices_dir, f"{name}.json")
        if not os.path.exists(src_path):
            print(f"[error] source profile missing: {src_path}", file=sys.stderr)
            return 1
        with open(src_path) as f:
            src = json.load(f)

        ref_text = src.get("reference_text")
        if not ref_text:
            print(f"[error] {name}.json missing reference_text (required for Qwen3)", file=sys.stderr)
            return 1

        ref_audio = src.get("reference_audio", f"{name}-ref.wav")

        for backend_name in NON_DEFAULT_BACKENDS:
            slug = backends.slug(backend_name)
            out_name = f"{name}-{slug}"
            out_path = os.path.join(args.voices_dir, f"{out_name}.json")

            if os.path.exists(out_path) and not args.force:
                print(f"[skip] {out_path} already exists")
                skipped += 1
                continue

            payload = {
                "name": out_name,
                "backend": backend_name,
                "reference_audio": ref_audio,
                "reference_text": ref_text,
                "session_id": None,
                "notes": f"Generated by reclone-flagship.py — shares ref WAV with {name}.json",
            }
            with open(out_path, "w") as f:
                json.dump(payload, f, indent=2)
            print(f"[write] {out_path}")
            written += 1

    print(f"\nDone: {written} written, {skipped} skipped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
